# https://github.com/tuananh/py-event-ruler/blob/main/.github/workflows/publish.yml
name: Build & Deploy
on:
  push:
    tags:
      - v*
env:
  PY_COLORS: "1"
  GOTRACEBACK: crash
  GO111MODULE: auto

jobs:
  build_linux_x86_64:
    # if: false
    name: Linux 310,311 x86_64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: copy setup.py
        run: cp setup_ci.py setup.py

      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        env:
          CIBW_BUILD: "cp3*_x86_64"
          CIBW_SKIP: "cp36-* cp37-* cp38-* cp39-* *-musllinux_x86_64"
          CIBW_ARCHS: "native"
          CIBW_ENVIRONMENT: "PATH=$PATH:/usr/local/go/bin RELEASE_VERSION=${RELEASE_VERSION}"
          CIBW_ENVIRONMENT_PASS_LINUX: "RELEASE_VERSION"
          CIBW_BEFORE_ALL_LINUX: |
            curl -o go.tar.gz https://dl.google.com/go/go1.22.9.linux-amd64.tar.gz
            tar -C /usr/local -xzf go.tar.gz
            go install github.com/go-python/gopy@v0.4.10
            go install golang.org/x/tools/cmd/goimports@v0.16.0
          CIBW_BUILD_VERBOSITY: 3 # Add verbose output

      - name: Upload atifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-amd64
          path: ./wheelhouse/*.whl

  # TODO: fails. is disabled using `if:false`
  build_linux_arm:
    if: false
    name: Linux 311,312 armv7l
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: copy setup.py
        run: cp setup_ci.py setup.py

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build wheels via Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./armv7l.Dockerfile
          push: false
          platforms: linux/armhf
          tags: armv7l:latest
          cache-from: type=ghane
          cache-to: type=gha,mode=min
          load: true
          build-args: |
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}

      - name: Extract output
        run: |
          docker run -v /tmp/output:/host armv7l:latest bash -c "cp /export/* /host/"
          tar -zcvf /tmp/output.tar.gz /tmp/output

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-arm
          path: /tmp/output/*.whl

  publish:
    name: Publish PyPI
    needs: [build_linux_x86_64, build_linux_arm]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
      - name: Collect all wheels
        run: |
          ls -R
          mkdir dist
          for f in $(find . -type f -name '*.whl'); do mv ${f} dist; done;
          ls -R dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./dist
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          print-hash: true
